### ISSUE TITLE
This is very weird 

### ISSUE THREAD

**Issue by SALTA7B** [7dpk/OpenCV-Chess-Bot#2]
1- Some times a add just get on screen then the bot print this is very weird i think it should wait 5 sec and try to detect again

2- can u make it just detect the all board and try play not just play from the start cuz when it stops i cant continue my game

3- add contrast and brightness  setting  cuz some boards the bot not detecting it 

+thx its the best bot i have ever try so simple

**Comment by 7dpk** [comment]
Hey there! I hope you had some fun trying out the board detection algorithm. Currently, the algorithm relies on simple sampling and convolution techniques instead of AI/ML to make it faster. However, I plan to include a piece detection model to improve the game's functionality.

Unfortunately, I'm still working on gathering enough 2D piece images to train the model properly, but once that's done, I'll be more than happy to implement it.

To improve the board detection, I'll be adding more configuration settings to tweak the contrast and threshold.

Thanks for giving it a go! I appreciate your support, and I'll be sure to work on it as soon as possible to address the detection issue.
